export const financialCommandSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    intent: {
      type: 'string',
      description: 'Choose the single financial/admin intent that exactly matches the transcript. Explicit account creation must use CREATE_ACCOUNT, never CREATE_TRANSACTION.',
      enum: [
        'CREATE_TRANSACTION',
        'UPDATE_TRANSACTION',
        'DELETE_TRANSACTION',
        'RESTORE_TRANSACTION',
        'FIND_TRANSACTION',
        'TRANSFER_MONEY',
        'CREATE_ACCOUNT',
        'UPDATE_ACCOUNT',
        'SET_ACCOUNT_OPENING_BALANCE',
        'ARCHIVE_ACCOUNT',
        'DELETE_ACCOUNT_CASCADE',
        'RESET_ACCOUNT',
        'CREATE_CATEGORY',
        'RESET_HOUSEHOLD_FINANCES',
        'GET_FINANCIAL_SUMMARY',
      ],
    },
    transaction_type: {
      type: ['string', 'null'],
      enum: ['EXPENSE', 'INCOME', 'TRANSFER', 'ADJUSTMENT', null],
    },
    amount: { type: ['number', 'null'], minimum: 0, description: 'Transaction/transfer amount only. Do not put an account opening balance here.' },
    currency: { type: ['string', 'null'] },
    date: { type: ['string', 'null'] },
    date_reference: {
      type: ['string', 'null'],
      enum: ['TODAY', 'YESTERDAY', null],
    },
    account_hint: { type: ['string', 'null'], description: 'For CREATE_ACCOUNT, this is the new account name. For CREATE_TRANSACTION, this is the existing payment account hint.' },
    source_account_hint: { type: ['string', 'null'] },
    destination_account_hint: { type: ['string', 'null'] },
    category_hint: { type: ['string', 'null'] },
    merchant_hint: { type: ['string', 'null'] },
    description: { type: ['string', 'null'] },
    selector: {
      type: ['object', 'null'],
      additionalProperties: false,
      properties: {
        description: { type: ['string', 'null'] },
        merchant: { type: ['string', 'null'] },
        relative_date: {
          type: ['string', 'null'],
          enum: ['TODAY', 'YESTERDAY', null],
        },
        date: { type: ['string', 'null'] },
        amount: { type: ['number', 'null'], minimum: 0, description: 'Amount of the existing transaction used only as a matching criterion.' },
      },
      required: ['description', 'merchant', 'relative_date', 'date', 'amount'],
    },
    changes: {
      type: ['object', 'null'],
      additionalProperties: false,
      properties: {
        amount: { type: ['number', 'null'], minimum: 0, description: 'Proposed new transaction amount for UPDATE_TRANSACTION.' },
        date: { type: ['string', 'null'] },
        account_hint: { type: ['string', 'null'], description: 'Proposed new existing account name/hint for UPDATE_TRANSACTION.' },
        category_hint: { type: ['string', 'null'] },
        merchant_name: { type: ['string', 'null'] },
        description: { type: ['string', 'null'] },
      },
      required: ['amount', 'date', 'account_hint', 'category_hint', 'merchant_name', 'description'],
    },
    account_selector: {
      type: ['object', 'null'],
      additionalProperties: false,
      properties: {
        name: { type: ['string', 'null'], description: 'Name of an existing account to select. Must be null for CREATE_ACCOUNT.' },
        account_type: {
          type: ['string', 'null'],
          enum: ['CASH', 'BANK', 'EWALLET', 'CREDIT_CARD', 'SAVINGS', 'OTHER', null],
        },
      },
      required: ['name', 'account_type'],
    },
    account_changes: {
      type: ['object', 'null'],
      additionalProperties: false,
      properties: {
        name: { type: ['string', 'null'] },
        opening_balance: { type: ['number', 'null'], minimum: 0, description: 'Opening balance for CREATE_ACCOUNT or SET_ACCOUNT_OPENING_BALANCE. Never a transaction amount.' },
      },
      required: ['name', 'opening_balance'],
    },
    account_type: {
      description: 'Type of a newly created account when clearly stated or strongly implied (for example Bank Mandiri => BANK, GoPay ewallet => EWALLET).',
      type: ['string', 'null'],
      enum: ['CASH', 'BANK', 'EWALLET', 'CREDIT_CARD', 'SAVINGS', 'OTHER', null],
    },
    category_name: { type: ['string', 'null'] },
    parent_category_hint: { type: ['string', 'null'] },
    category_transaction_type: {
      type: ['string', 'null'],
      enum: ['EXPENSE', 'INCOME', 'BOTH', null],
    },
    confidence: { type: 'number', minimum: 0, maximum: 1 },
  },
  required: [
    'intent',
    'transaction_type',
    'amount',
    'currency',
    'date',
    'date_reference',
    'account_hint',
    'source_account_hint',
    'destination_account_hint',
    'category_hint',
    'merchant_hint',
    'description',
    'selector',
    'changes',
    'account_selector',
    'account_changes',
    'account_type',
    'category_name',
    'parent_category_hint',
    'category_transaction_type',
    'confidence',
  ],
} as const

const field = (valueType: string) => ({
  type: 'object',
  additionalProperties: false,
  properties: {
    value: { type: [valueType, 'null'] },
    confidence: { type: 'number', minimum: 0, maximum: 1 },
    needs_review: { type: 'boolean' },
  },
  required: ['value', 'confidence', 'needs_review'],
})

export const receiptSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    merchant: field('string'),
    transaction_date: field('string'),
    total: field('number'),
    subtotal: field('number'),
    tax: field('number'),
    discount: field('number'),
    payment_method: field('string'),
    category_hint: field('string'),
    items: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          name: { type: ['string', 'null'] },
          quantity: { type: ['number', 'null'] },
          unit_price: { type: ['number', 'null'] },
          total: { type: ['number', 'null'] },
          confidence: { type: 'number', minimum: 0, maximum: 1 },
        },
        required: ['name', 'quantity', 'unit_price', 'total', 'confidence'],
      },
    },
  },
  required: ['merchant', 'transaction_date', 'total', 'subtotal', 'tax', 'discount', 'payment_method', 'category_hint', 'items'],
} as const

export const financialQuerySchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    metric: { type: 'string', enum: ['expense', 'income', 'net_cash_flow'] },
    category_hint: { type: ['string', 'null'] },
    merchant_hint: { type: ['string', 'null'] },
    from: { type: 'string' },
    to: { type: 'string' },
  },
  required: ['metric', 'category_hint', 'merchant_hint', 'from', 'to'],
} as const
